### ISSUE TITLE
Hocon schema does not support referencing external type

### ISSUE THREAD

**Issue by Rory-Z** [emqx/hocon#104]
I want to reference the external type in my schema file, like this:
```erl
-type url() :: emqx_http_lib:uri_map().

-reflect_type([ permission/0
              , action/0
              , url/0
              ]).

-typerefl_from_string({url/0, emqx_http_lib, uri_parse}).

-export([ structs/0
        , fields/1
        ]).

structs() -> ["http"].

fields(http) ->
    [ {url, #{type => url()} }
    ];
```

But I got error:
```erl
escript: exception error: undefined function emqx_http_lib:uri_map/0
  in function  emqx_authz_schema:url/0 (emqx_authz_schema.erl, line 7)
  in call from emqx_authz_schema:fields/1 (emqx_authz_schema.erl, line 26)
  in call from hocon_schema:map_field/4 (hocon_schema.erl, line 436)
  in call from hocon_schema:do_map_union/4 (hocon_schema.erl, line 541)
  in call from hocon_schema:map_field/4 (hocon_schema.erl, line 452)
  in call from hocon_schema:do_map_array/4 (hocon_schema.erl, line 552)
  in call from hocon_schema:map_field/4 (hocon_schema.erl, line 462)
```

Is there any way I can use external type?

**Comment by k32** [comment]
Hello @Rory-Z,

Did you include `-reflect_type([uri_map/0])` annotation in `emqx_http_lib` module?

**Comment by Rory-Z** [comment]
> Hello @Rory-Z,
> 
> Did you include `-reflect_type([uri_map/0])` annotation in `emqx_http_lib` module?
> This annotation works via parse transform, so unfortunately it has a limitation that it cannot work across different modules.

Cool, It's worked !
But I had a new problem:
```erl
escript: exception error: undefined function unicode:chardata/0
  in function  emqx_http_lib:uri_map/0 (emqx_http_lib.erl, line 33)
  in call from emqx_authz_schema:url/0 (emqx_authz_schema.erl, line 7)
  in call from emqx_authz_schema:fields/1 (emqx_authz_schema.erl, line 33)
  in call from hocon_schema:map_field/4 (hocon_schema.erl, line 436)
  in call from hocon_schema:map_one_field/4 (hocon_schema.erl, line 424)
  in call from hocon_schema:map_fields/4 (hocon_schema.erl, line 419)
  in call from hocon_schema:do_map_union/4 (hocon_schema.erl, line 541)
```
I can't modify `unicode` module because it's the source code of otp, is there any other way?

**Comment by k32** [comment]
> I can't modify unicode module because it's the source code of otp, is there any other way?

You are right. Let me check if there is an equiavalent type. Otherwise, typerefl should be patched to support this type

**Comment by k32** [comment]
@Rory-Z Could you please share the working version of `emqx_authz_schema.erl` for more context?

**Comment by Rory-Z** [comment]
> @Rory-Z Could you please share the work in progress version of `emqx_authz_schema.erl` for more context where you see the error?

Yes, you can check `emqx_authz_schema.erl ` in [this](https://github.com/Rory-Z/emqx/commit/059a8e9124ebd1313bdb3837db9498586dee4a02#diff-c33208341c90261dc2a216728c64d4f25ba3428986959926098a23cfed6cc827R7), But I'm working on it, so the contents of the file may be modified

**Comment by k32** [comment]
Thanks. Fix for the problem: https://github.com/k32/typerefl/pull/25

**Comment by Rory-Z** [comment]
> Thanks. Fix for the problem: [k32/typerefl#25](https://github.com/k32/typerefl/pull/25)

Cool ! When can I use it in `emqx/emqx` master branch?

**Comment by k32** [comment]
You can bump hocon version to 0.9.7, it should include the fix.

**Comment by Rory-Z** [comment]
> You can bump hocon version to 0.9.7, it should include the fix.

Cool !

**Comment by Rory-Z** [comment]
Hi, @k32 
I updated `hocon` to 0.9.7 and `typefl` to 0.8.0 and the problem still exists.

And this error appears again: `escript: exception error: undefined function emqx_http_lib:uri_map/0` even though I include  `-reflect_type([uri_map/0])` in the `emqx_http_lib` module

**Comment by k32** [comment]
Hi @Rory-Z ,
Could you push your the work-in-progress code somewhere, so I could try to reproduce the problem?

**Comment by Rory-Z** [comment]
> Hi @Rory-Z ,
> Could you push your the work-in-progress code somewhere, so I could try to reproduce the problem?

Hi, you can check my code in this: https://github.com/Rory-Z/emqx/tree/chore/demo-authz-conf, this branch will not be updated until you resolve the issue

**Comment by k32** [comment]
It looks like code on your branch checks out the unpatched version emqx_http_lib that doesn't include the reflected types.

But I wonder if it makes sense to make `typerefl` a dependency `emqx_http_lib`. If I understand your intentions correctly, you want to verify that the URL string provided by the user in the config is correct. `emqx_http_lib` already does all the necessary validation in the `uri_parse` function. So it does not make much sense to do type check of its return value (we're assuming that `emqx_http_lib` is correct).

With that in mind, perhaps it should be sufficient to define `url()` type in `emqx_authz_schema` module like this:

```
-type url() :: map().

-typerefl_from_string({url/0, emqx_http_lib, uri_parse}).
```

**Comment by Rory-Z** [comment]
> It looks like code on your branch checks out the unpatched version emqx_http_lib that doesn't include the reflected types.

Yes, you need to add `-reflect_type([uri_map/0])` in the `emqx_http_lib` module manually, and I still encounter the error after adding: `escript: exception error: undefined function emqx_http_lib:uri_map/0`, I think that's a problem.

> With that in mind, perhaps it should be sufficient to define url() type in emqx_authz_schema module like this:

Cool, that's a great idea.
But I think the schema file should describe the configuration in as much detail as possible, and I still want to use `-type url() :: emqx_http_lib:uri_map()` if I can.

**Comment by k32** [comment]
Fix is coming soon.

**Comment by k32** [comment]
I tested your branch with the following changes, and everything seems to be working:
```
    , {hocon, {git, "https://github.com/emqx/hocon.git", {tag, "0.10.2"}}}
    , {emqx_http_lib, {git, "https://github.com/emqx/emqx_http_lib.git", {tag, "0.3.0"}}}
```

**Comment by Rory-Z** [comment]
> Hi @Rory-Z , thanks for the patience.
> 
> I tested your branch with the following changes, and everything seems to be working:
> 
> ```
>     , {hocon, {git, "https://github.com/emqx/hocon.git", {tag, "0.10.2"}}}
>     , {emqx_http_lib, {git, "https://github.com/emqx/emqx_http_lib.git", {tag, "0.3.0"}}}
> ```

Cool ! It worked ! thx !

I have another question, I noticed that you introduced `-reflect_type([uri_map/0, uri/0])` in `emqx_http_lib`, is this required? Can I use a type like `unicode:chardata/0` in my schema file?

**Comment by k32** [comment]
> I have another question, I noticed that you introduced -reflect_type([uri_map/0, uri/0]) in emqx_http_lib, is this required? Can I use a type like unicode:chardata/0 in my schema file?

In the ideal case, every type that is used in schema is created using `reflect_type` annotation. However, it's not always possible to add this annotation to a module, in this case `-typerefl_surrogate` annotation can be used (see https://github.com/k32/typerefl/blob/master/include/types.hrl#L19) to replace the type.

**Comment by Rory-Z** [comment]
> > I have another question, I noticed that you introduced -reflect_type([uri_map/0, uri/0]) in emqx_http_lib, is this required? Can I use a type like unicode:chardata/0 in my schema file?
> 
> In the ideal case, every type that is used in schema is created using `reflect_type` annotation. However, it's not always possible to add this annotation to a module, in this case `-typerefl_surrogate` annotation can be used (see https://github.com/k32/typerefl/blob/master/include/types.hrl#L19) to replace the type.

So cool！
