### ISSUE TITLE
How to add any key to map() by fields/1

### ISSUE THREAD

**Issue by Rory-Z** [emqx/hocon#105]
Hi, Guys

I create `fields/1` function like this:

```erlang
fields(headers) ->
    [ {'Accept',            #{type => binary(), default => <<"application/json">>}}
    , {'Accept-Encoding',   #{type => binary(), default => <<"gzip, deflate">>}}
    , {'Accept-Language',   #{type => binary(), default => <<"en-US">>}}
    , {'Authorization',     #{type => binary(), nullable => true}}
    , {'Cache-Control',     #{type => binary(), default => <<"no-cache">>}}
    , {'Connection',        #{type => binary(), default => <<"keep-alive">>}}
    , {'Content-Type',      #{type => binary(), default => <<"application/json">>}}
    , {'Keep-Alive',        #{type => binary(), default => <<"timeout=5">>}}
    ];
```

I have defined some http headers, how should I update this method if I want to let users freely add other header?

**Comment by zmstone** [comment]
Maybe use a `map()` type and implement a validator instead of relying on field schema.

**Comment by Rory-Z** [comment]
> Maybe use a `map()` type and implement a validator instead of relying on field schema.

But I want to set default values for some keys in `map()`, how can I do that?

Can the `validations/0` function help me to do this?

**Comment by zmstone** [comment]
Two alternatives: 1.  Use another map() field and merge two fields at runtime 
2. Implement a converter callback to fill in defaults
