### ISSUE TITLE
hoconsc:ref(Module, Name) won't call Module:validation/0

### ISSUE THREAD

**Issue by tigercl** [emqx/hocon#107]
When I use `hoconsc:ref(Module, Name)` to refer to the type defined in `Module` in a schema, `Module:validation/0` will not be called?

**Comment by zmstone** [comment]
Need a fix

**Comment by zmstone** [comment]
a second thought, it might be more complex than it appears.

external validations are only done at root level.
for struct level validations, they can be added as validator callbacks.
