### ISSUE TITLE
Substitution-like strings in keys are parsed incorrectly

### ISSUE THREAD

**Issue by thalesmg** [emqx/hocon#269]
According to the [HOCON spec](https://github.com/lightbend/config/blob/5d6a46631c7ca1d617de02459bd62af5b875073b/HOCON.md#substitutions):

> Substitutions are not parsed inside quoted strings.

### Expected behavior

```elixir
iex> :hocon.binary(~s|"${.x}" = 1|)      
{:ok, %{"${.x}" => 1}}
```

### Actual behavior

```elixir
iex> :hocon.binary(~s|"${.x}" = 1|)      
{:ok, %{"${" => %{"x}" => 1}}}
```

**Comment by zmstone** [comment]
Substitutions are only allowed in field values and array elements (value concatenations), they are not allowed in keys or nested inside other substitutions (path expressions).

**Comment by thalesmg** [comment]
> Substitutions are only allowed in field values and array elements (value concatenations), they are not allowed in keys or nested inside other substitutions (path expressions).

Sure, that's another reason why it should have parsed the key as a single string.  I'm not trying to do substitution here in this example.
