### ISSUE TITLE
Is the "Optional system or env variable overrides" supported here?

### ISSUE THREAD

**Issue by jonathan-dev** [emqx/hocon#301]
Is the "Optional system or env variable overrides" from the hocon spec supported here?
https://github.com/lightbend/config?tab=readme-ov-file#optional-system-or-env-variable-overrides
I can't get it to work when configuring emqx which should be using this lib right?

I am using the v5.8.3 docker image

**Comment by id** [comment]
Yes. Please refer to the official documentation https://docs.emqx.com/en/emqx/latest/configuration/configuration.html#environment-variables

**Comment by jonathan-dev** [comment]
I was wondering about the hocon syntax: `${?FORCED_BASEDIR}` refering to the environment variable `FORCED_BASEDIR` that ist discussed in the docs you linked to or is it? There it is just talking about that I can set certain variables that will set certain settings...

**Comment by id** [comment]
ping @zmstone

**Comment by zmstone** [comment]
We have no plan to implement environment variable value interpolation in this lib.

**Comment by jonathan-dev** [comment]
> We have no plan to implement environment variable value interpolation in this lib.

could you list this under _Divergence from Spec and Caveats_ in the `readme.md` would have been helpful for me

Thanks

**Comment by zmstone** [comment]
https://github.com/emqx/hocon/pull/302
