### ISSUE TITLE
Convert Erlang term back to HOCON

### ISSUE THREAD

**Issue by terry-xiaoyu** [emqx/hocon#69]
When generating erlang terms from hocon files, the hocon schema transforms the values according to the type, which is good.

For example if we specified `fun (type) -> ip_port();` the value will be converted from `binary()` to `ip_port()` after all validation passed. 

But if we tried to convert the generated Erlang term to JSON using `jsx:encode(Term)`, it fails because `ip_port()` is of type tuple(). 

I would appreciate if hocon schema supports converting the Erlang term back to json (or hocon), and do the inverse operation of `tyeprefl:from_string/2`, i.e. converting the `ip_port()` back to `binary()`.

**Comment by zmstone** [comment]
maybe we should try avoid using such types for the use cases which require dumping configs back to HOCON or JSON format.

**Comment by terry-xiaoyu** [comment]
It's hard.. For example if I defined a schema like:
```
fun (type) -> string();
```
The value is converted to list() after generating, but I have to convert it back to binary() because that's the correct `string` type what `jsx` and `jiffy` accepts.

I can do this work at the application level but I think the better place to do this is in the hocon schema.

**Comment by zmstone** [comment]
the only reason we have list for string is to be backward compatible with cuttlefish.
for schemas without such concern, we can add a `string_format => binary` option for `hocon:load/2` and `hocon:binary/2`

**Comment by terry-xiaoyu** [comment]
Not really, some old-fashion APIs like `httpc:request/1` may need `string()` rather than `binary()` as their arguments. We need string() in such cases.

**Comment by zmstone** [comment]
you can’t have it in both ways
