### ISSUE TITLE
“a.b = c ” does not work in the list

### ISSUE THREAD

**Issue by Rory-Z** [emqx/hocon#93]
I created a file that reads: `a: [ {b.c = 1} ]` , When I executed `hocon:load/1`, I got it: `{ok,#{<<"a">> => [#{<<"b">> => 1}]}}` , It looks like `c` is missing

When I change the contents of the file to: `a: {b.c = 1}` and executed `hocon:load/1` again, I got the correct result: `{ok,#{<<"a">> => #{<<"b">> => #{<<"c">> => 1}}}}`

**Comment by z8674558** [comment]
fixed in 0.9.3
