### ISSUE TITLE
It looks like the content of the comments in the file affects the `hocon:load/1` function

### ISSUE THREAD

**Issue by Rory-Z** [emqx/hocon#98]
I created a file that reads: 
```
a: [
    {b:1},
    # {}
    {c:2}
]
```
When I executed `hocon:load/1`, I got it: 
```erlang
{ok,#{<<"a">> => [#{<<"b">> => 1,<<"c">> => 2}]}}
```
This is wrong and `b` and `c` should not be in a map

When I delete comments in a file:
```
a: [
    {b:1},
    {c:2}
]
```
and executed `hocon:load/1` again, I got the correct result: 
```erlang
{ok,#{<<"a">> => [#{<<"b">> => 1},#{<<"c">> => 2}]}}
```

It looks like the content of the comments in the file affects the `hocon:load/1` function

**Comment by z8674558** [comment]
fixed in `0.9.4`
